[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "items"
dynamic = ["version"]
authors = [
  { name="Veit Schiele", email="veit@cusy.io" },
]
description = ""
readme = "README.rst"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]
dependencies = [
    "tinydb",
    "typer",
]

[project.optional-dependencies]
tests = [
    "coverage[toml]",
    "pytest>=6.0",
    "faker",
]
docs = [
    "furo",
    "sphinxext-opengraph",
    "sphinx-copybutton",
    "sphinx_inline_tabs"
]
dev = [
    "items[tests, docs]",
    "pre-commit"
]

[tool.hatch.version]
path = "src/items/__init__.py"

[project.scripts]
items = "items:app"
